[package]
name = "k8p"
version = "0.4.4"
edition = "2021"
license = "MIT"
authors = ["Ed Sweeney <ed@onextent.com>"]
description = "A cli tool for inspecting containers in Kubernetes"
keywords = ["kubernetes", "commandline", "k8s", "prometheus", "metrics"]
documentation = "https://docs.rs/k8p"
repository = "https://github.com/navicore/k8p"

[[bin]]
name = "k8p"
path = "src/main.rs"

[dependencies]
uuid = { version = "1.4.1", features = [ "v4" ] }
regex = "1.9"
kube = { version = "0.84.0", features = ["runtime", "derive", "client", "ws"] }
k8s-openapi = { version = "0.19.0", features = ["v1_26"] }
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread", "signal"] }
csv = "1.2"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
futures = "0.3"
tokio-util = "0.7"
anyhow = "1.0.72"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sqlx = { version = "0.7", features = [ "sqlite", "runtime-tokio-native-tls" ] }
