[package]
name = "navipod"
version = "0.5.1"
edition = "2021"
license = "MIT"
authors = ["Ed Sweeney <ed@onextent.com>"]
description = "A cli tool for inspecting containers in Kubernetes"
keywords = ["kubernetes", "commandline", "k8s", "prometheus", "metrics"]
documentation = "https://docs.rs/navipod"
repository = "https://github.com/navicore/navipod"

[[bin]]
name = "navipod"
path = "src/main.rs"

[dependencies]
uuid = { version = "1.7.0", features = [ "v4" ] }
regex = "1.10"
kube = { version = "0.87.2", features = ["runtime", "derive", "client", "ws"] }
k8s-openapi = { version = "0.21.0", features = ["v1_26"] }
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "signal"] }
csv = "1.3"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
futures = "0.3"
tokio-util = "0.7"
anyhow = "1.0.79"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
sqlx = { version = "0.7", features = [ "sqlite", "runtime-tokio-native-tls" ] }
clap_complete = "4.4.8"
